name: Build PDF

on:
  push:
    branches:
      - main
    paths:
      - 'main.tex'

jobs:
  build:
    name: latexmk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Generate PDF document
        uses: hspaans/latexmk-action@v2.1.1
        with:
          format: pdf
          filename: main.tex
